//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KTS_Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Kts_dataEntities : DbContext
    {
        public Kts_dataEntities()
            : base("name=Kts_dataEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<answer_images> answer_images { get; set; }
        public virtual DbSet<answer> answers { get; set; }
        public virtual DbSet<Department> Departments { get; set; }
        public virtual DbSet<question_difficulty> question_difficulty { get; set; }
        public virtual DbSet<question_images> question_images { get; set; }
        public virtual DbSet<question_importance> question_importance { get; set; }
        public virtual DbSet<question_levels> question_levels { get; set; }
        public virtual DbSet<question> questions { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<subject> subjects { get; set; }
        public virtual DbSet<Test_questions> Test_questions { get; set; }
        public virtual DbSet<Test_versions> Test_versions { get; set; }
        public virtual DbSet<User_Tests> User_Tests { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<subject_difficulty_importance> subject_difficulty_importance { get; set; }
        public virtual DbSet<test_subjects_difficulty> test_subjects_difficulty { get; set; }
        public virtual DbSet<user_test_subjects> user_test_subjects { get; set; }
    }
}
