//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KTS_Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class subject_difficulty_importance
    {
        public long difficulty_importance_id { get; set; }
        public Nullable<long> test_subject_difficulty_id { get; set; }
        public string importance_code { get; set; }
        public int no_of_questions { get; set; }
    
        public virtual question_importance question_importance { get; set; }
        public virtual test_subjects_difficulty test_subjects_difficulty { get; set; }
    }
}
