//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KTS_Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Test_questions
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Test_questions()
        {
            this.Test_versions = new HashSet<Test_versions>();
        }
    
        public long test_question_id { get; set; }
        public Nullable<long> test_id { get; set; }
        public Nullable<long> question_id { get; set; }
    
        public virtual question question { get; set; }
        public virtual User_Tests User_Tests { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Test_versions> Test_versions { get; set; }
    }
}
