//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KTS_Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_test_subjects
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public user_test_subjects()
        {
            this.test_subjects_difficulty = new HashSet<test_subjects_difficulty>();
        }
    
        public long user_test_subject_id { get; set; }
        public Nullable<long> test_id { get; set; }
        public long subject_id { get; set; }
        public int no_of_questions { get; set; }
    
        public virtual subject subject { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<test_subjects_difficulty> test_subjects_difficulty { get; set; }
        public virtual User_Tests User_Tests { get; set; }
    }
}
