//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KTS_Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_Tests
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User_Tests()
        {
            this.Test_questions = new HashSet<Test_questions>();
            this.user_test_subjects = new HashSet<user_test_subjects>();
            this.Test_versions1 = new HashSet<Test_versions>();
        }
    
        public long test_id { get; set; }
        public int total_questions { get; set; }
        public int total_time_minutes { get; set; }
        public string status { get; set; }
        public int test_versions { get; set; }
        public string test_creator { get; set; }
        public long user_Id { get; set; }
        public System.DateTime insertion_timestamp { get; set; }
        public string description { get; set; }
        public int total_marks { get; set; }
        public Nullable<int> question_level_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Test_questions> Test_questions { get; set; }
        public virtual User User { get; set; }
        public virtual question_levels question_levels { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<user_test_subjects> user_test_subjects { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Test_versions> Test_versions1 { get; set; }
    }
}
